### ISSUE TITLE
Migrate uTorrent statistics to qbt

### ISSUE THREAD

**Issue by stdedos** [rumanzo/bt2qbt#12]
Hello there! Fancy seeing you here!

Although a bit scared, given the bitbucket repo link does not work for some reason, and I got scared you closed-source this!

Have you considered / is it easy to migrate the uTorrent statistics to qbt?

(At this point, I am looking to merge them, but the underlying question "have you figured out how qbt stores its statistics?" remains)

**Comment by rumanzo** [comment]
Hi! I moved to github because it is a more common platform and it has become possible to create private repositories.
Regarding the import of statistics, I watched how it is implemented in qBittorrent, it uses the function in Qt, I did not understand how it works in pure Qt, and using the Qt function in golang is difficult, unstable and will need to install the whole framework for build and greatly increase the size of the final binary file

**Comment by stdedos** [comment]
Oh 😕 I see.

Let's see if I somehow get them to use a non-Qt data type https://github.com/qbittorrent/qBittorrent/issues/12782

**Comment by stdedos** [comment]
Follow https://github.com/qbittorrent/qBittorrent/issues/13386 for updates.

Also ... from the looks of what's said, I understood that _there could be a tool that does that actually already_. I am definitely not familiar with qbt's forums; you may dig in if you want.
